version: "3.3"

services:
  php-cli:
    image: exozet/php-fpm:7.4
    user: www-data
    entrypoint: bash
    volumes:
      - ./:/usr/src/app:cached
      - ./.docker/cache/composer:/composer/cache/
    env_file:
      - ./.docker/common.env
      - .env
    ports:
      - 9000

  php-fpm:
    image: exozet/php-fpm:7.4
    user: www-data
    volumes:
      - ./:/usr/src/app:cached
      - ./.docker/cache/composer:/composer/cache/
    env_file:
      - ./.docker/common.env
      - .env

  ngrok:
    image: wernight/ngrok
    depends_on:
      - nginx
    ports:
      - "4040"
    env_file:
      - .env.local

  nginx:
    image: nginx:1.13.5-alpine
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
      - "4040"
    volumes:
      - ./:/usr/src/app:cached
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/default.conf